<table class="container">
	<tr>
		<td class="container-padding header" >
			<?php echo $this->config->application->company;?>
		</td>
	</tr>
	<tr>
		<td class="container-padding content">
    		<br>
    			<div class="title">You Username is: <?php echo $username; ?> <br />
    				Please confirm your email. 
    			</div>
    		<br>
    		<div class="body-text">
    			<p><strong style="font-size: 18px; color: #444444;"> <a class="yshortcuts" href="http://<?php echo $publicUrl.$confirmUrl;?>">Click here</a></strong> to Confirm you email and Create a password</p>
    		</div>
    		<br />
    		Madina Masjid Technical Team
		</td>
	</tr>
</table>