<?php echo $this->getContent(); ?>

<?php if ($this->auth->getUser()):?>
<div class="portlet-body">
	<h4 class="block">Welcome <?php echo $this->auth->getName(); ?></h4>
	<ul class="list-unstyled">
		<li><?php echo $this->tag->linkTo(["dashboard", "Dashboard", "class" => "btn btn-transparent"]); ?></li>
		<li><?php echo $this->tag->linkTo(["session/logout", "Logout", "class" => "btn btn-transparent"]); ?></li>
	</ul>
</div>
<?php else:?>
<form method="post" class="login-form" autocomplete="off">
<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
<h3 class="form-title font-green">Sign In</h3>
<div class="form-group">
 	<label class="control-label visible-ie8 visible-ie9">Username</label>
 	<?php echo $form->render('username');?>	
</div>
<div class="form-group">
 	<label class="control-label visible-ie8 visible-ie9">Password</label>
 	<?php echo $form->render('password');?>
</div>

<div class="form-actions">
	<?php echo $form->render('Login');?>
	<!-- <input type="submit" class="btn red uppercase" name="login" value="Login" /> -->
	<label class="rememberme check mt-checkbox mt-checkbox-outline">
		<?php echo $form->render('remember');?> Remember me
		<span></span>
	</label>
	<?php echo $this->tag->linkTo(["session/forgotPassword", "Forgot password?", "class" => "forget-password"]); ?>
</div>
 </form>
 
 <?php endif;?>