<?php echo $this->getContent(); ?>
<div class="row">
	<div class="col-md-6">
		<div class="portlet light ">
			<div class="portlet-title">
				<div class="caption">Change Password</div>
			</div>
			<div class="portlet-body form">
				<form method="post" class="form-horizontal" autocomplete="off">
					<?php echo $form->render('csrf');?>
					<div class="form-body">
						<div class="form-group">
							<label for="id" class="control-label col-md-3">Password</label>
							<div class="col-md-9"><?php echo $form->render('password');?></div>
						</div>
						<div class="form-group">
							<label for="id" class="control-label col-md-3">Confirm Password</label>
							<div class="col-md-9"><?php echo $form->render('confirmPassword');?></div>
						</div>
						
						<div class="form-group">
							<label for="id" class="control-label col-md-3"></label>
							<div class="col-md-9"><?php echo $form->render('Change Password');?></div>
						</div>
					</div>					
				</form>
			</div>
		</div>
	</div>
</div>