<?php
 echo $this->getContent();?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light ">
			<div class="portlet-title">
            	<div class="caption bold font-blue-soft uppercase">Customer List</div>
            	<div class="actions">
            		<?php echo $this->tag->linkTo(["users/create", 'new User', "class" => "btn btn-transparent btn-sm"]); ?>
            	</div>
      		</div>
      		<div class="portlet-body">
      			<table class="table table-bordered table-striped table-condensed table-light" id="sample_3">
					<thead>
						<tr>							
							<th>Name</th>
                          	<th>Username</th>
                        	<th>Email</th>
				            <th>Profile</th>
				            <th>Banned?</th>
				            <th>Suspended?</th>
				            <th>Confirmed?</th>
				            <th class="pull-right">Actions</th>
                  		</tr>
            		</thead>
            		<tbody>
                		<?php foreach ($users as $user):?>
                		<tr>
                			<td><?php echo $user->name;?></td>
                			<td><?php echo $user->username;?></td>
                			<td><?php echo $user->email;?></td>
                			<td><?php echo $user->profile->name?></td>
                			<td><?php echo $user->banned == 'Y' ? 'Yes' : 'No'; ?></td>
                			<td><?php echo $user->suspended == 'Y' ? 'Yes' : 'No';?></td>
                			<td><?php echo $user->active == 'Y' ? 'Yes' : 'No';?></td>
                			<td class="pull-right">
                				<?php echo $this->tag->linkTo(["users/edit/$user->id", '<i class="icon-pencil font-green"></i>', "class" => "btn-xs"]); ?>
                				<?php echo $this->tag->linkTo(["users/delete/$user->id", '<i class="fa fa-trash-o font-red"></i>', "class" => 'btn-xs', 'title' => 'Delete User', 'onclick' => "return confirm('Are you sure you want to Delete this user?')"]); ?>
                			</td>
                		</tr>
                		<?php endforeach;?>
                	</tbody>              		
             	</table>
      		</div>
		</div>
	</div>
</div>