
<?php echo $this->getContent() ?>

<form method="post">
<div class="row">
	<div class="col-md-12">
		<div class="portlet light ">
			<div class="portlet-title">
				<div class="caption">Manage Permissions </div>
			</div>
		<div class="portlet-body">
			<div class="row">
			<div align="center">
				<div class="col-lg-6 col-md-6 col-xm-6 col-xs-12">
					<div class="form-group">
						<label class="control-label col-md-3">Profile</label>
						<div class="col-md-9"><?php echo $this->tag->select(['profileId', $profiles, 'using' => ['id', 'name'], 'class' => 'form-control ', 'useEmpty' => true, 'emptyText' => '...', 'emptyValue' => '']) ?></div>
					</div>
				</div>
				<div class="col-lg-6 col-md-6 col-xm-6 col-xs-12">
					<?php echo $this->tag->submitButton(['Search', 'class' => 'btn btn-primary']) ?>
				</div>
			</div>
			</div>
			<?php if ($this->request->isPost() && $profile) { ?>
			<?php foreach ($this->acl->getResources() as $resource => $actions) { ?>
				<h3><?php echo $resource ?></h3>
				<table class="table table-bordered table-striped">
					<thead>
						<tr>
							<th width="5%"></th>
							<th>Description</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($actions as $action) { ?>
						<tr>
							<td align="center"><input type="checkbox" name="permissions[]" value="<?php echo $resource . '.' . $action ?>"  <?php if (isset($permissions[$resource . '.' . $action])) { ?> checked="checked" <?php } ?>></td>
							<td><?php echo $this->acl->getActionDescription($action) . ' ' . $resource ?></td>
						</tr>
						<?php } ?>
					</tbody>
				</table>
			
			<?php } ?>
			<?php } ?>
		</div>
		</div>
	</div>
</div>
					


</form>