<!DOCTYPE html>
<html lang="en">
	<head>
		<title><?php echo $this->config->companydata->title;?><?php echo isset($pagetitle)? $pagetitle: null;  ?></title>
		<meta content="width=device-width, initial-scale=1.0 , minimal-ui" name="viewport">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta content="" name="description" />
        <meta content="Cleartwo - Asif Iqbal" name="author" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        
        <?php echo $this->assets->outputCss("mandatorycss"); ?>
        <!--  PAGE LEVEL -->
        <?php if (isset($table)): ?>
        	<!--<link href="table.css" rel="stylesheet" type="text/css" />-->
        	 <link href="/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
        	<link href="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
        <?php if (isset($formassets)):?>
        <link href="/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
        <link href="/assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
        <?php if (isset($model)):?>
        <link href="/assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css" />
        <link href="/assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
        <?php if (isset($edit)):?>
        <link href="/assets/global/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
        <?php if (isset($login)):?>
        	<link href="/assets/pages/css/login.min.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
        <?php if (isset($invoice)):?>
        	<link href="/assets/pages/css/invoice-2.min.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
        <?php if (isset($profile)):?>
        <link href="/assets/pages/css/profile-2.min.css" rel="stylesheet" type="text/css" />        
        <?php endif;?>
        <!--  END PAGE LEVEL -->
        <?php echo $this->assets->outputCss("globelcss"); ?>
        <?php echo $this->assets->outputCss("layoutcss"); ?>
	</head>
		
        <?php echo $this->getContent(); ?>
    
   
    	<?php echo $this->assets->outputJs("corejs"); ?>
    	
    	 <!--  PAGE LEVEL -->
    	<?php if (isset($table)): ?>
    		<script src="/assets/global/scripts/datatable.min.js" type="text/javascript"></script>
    		<script src="/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
    		<script src="/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
    		<script src="/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
        <?php endif;?>
        <?php if (isset($repeat)): ?>
        	<script src="/assets/global/plugins/jquery-repeater/jquery.repeater.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($formassets)):?>
        <script src="/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/jquery.input-ip-address-control-1.0.min.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($angular) OR isset($angularfull)):?>
        <script src="https://cdn.jsdelivr.net/alasql/0.3/alasql.min.js"></script>
    	<script src="/assets/global/plugins/angularjs/angular.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/angularjs/angular-sanitize.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/angularjs/angular-touch.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/angularjs/plugins/angular-ui-router.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/angularjs/plugins/ocLazyLoad.min.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/angularjs/plugins/ui-bootstrap-tpls.min.js" type="text/javascript"></script>
    	<!-- <script src="https://code.angularjs.org/1.5.5/angular.js"></script>
    	<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-sanitize/1.6.2/angular-sanitize.min.js"></script> -->
        
        <?php endif;?>
        <?php if (isset($edit)):?>
        <script src="/assets/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($model)):?>
        <script src="/assets/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
        <script src="/assets/global/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>
        <?php endif;?>
        
        <!--  End PAGE LEVEL -->
    	<?php echo $this->assets->outputJs("appjs"); ?>
    	
    	<!--  Configuration -->
    	<?php if (isset($table)): ?>
    		<script src="/assets/pages/scripts/table-datatables-buttons.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($repeat)): ?>
        	<script src="/assets/pages/scripts/form-repeater.js" type="text/javascript"></script>
        	
        <?php endif;?>  
        <?php if (isset($formassets)):?>
        <script src="/assets/pages/form.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($model)):?>
        <script src="/assets/pages/scripts/ui-extended-modals.min.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($edit)):?>
        <script src="/assets/pages/scripts/form-editable.min.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($login)):?>
        	<script src="/assets/pages/scripts/login.min.js" type="text/javascript"></script>
        <?php endif;?>
        <!--  END Configuration -->
        <?php if (isset($custom)):?>
        	<script src="/assets/pages/customerajax.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($supplierjs)):?>
        	<script src="/assets/pages/supplierajax.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($angular)):?>angularfull
        	<script src="/assets/pages/angularprinting.js" type="text/javascript"></script>
        <?php endif;?>
        <?php if (isset($angularfull)):?>
        	<script src="/assets/pages/angularfullprinting.js" type="text/javascript"></script>
        <?php endif;?>
    	<?php echo $this->assets->outputJs("layoutjs"); ?>
    	
    </body>
</html>

