<?php use App\Models\Mongo\Students_m;

 echo $this->getContent();?>

<div class="row">
	<div class="col-md-12">
		<div class="portlet light ">
			<div class="portlet-title">
            	<div class="caption bold font-blue-soft uppercase">Fees List</div>
            	<div class="actions">
            		
            	</div>
      		</div>
      		<div class="portlet-body">
      			<table class="table table-bordered table-striped table-condensed table-light" id="sample_3">
					<thead>
						<tr class="uppercase">							
							<th>Student name</th>
							<th>Date Due</th>
                          	<th>status</th>
                          	<th><span class="pull-right">Action</span></th>
                  		</tr>
            		</thead>
            		<tbody>
                		<?php
                		   if (!empty($students)):
                		   foreach ($students as $key): $student = (string)$key->_student;
                		   if (isset($key->payment_status) && $key->payment_status == 'Unpaid'):
                		?>
                		<tr>			
                			<td><?php echo isset($student) ? Students_m::GetFullname($student): null;?></td>
                			<td><?php echo $key->due_date ? Students_m::Displaydate($key->due_date) : null;?></td>
                			<td><?php echo $key->payment_status ? $key->payment_status: null;?></td>
                			<td class="pull-right">                				
                			</td>			
                		</tr>
                		<?php  endif; endforeach; endif;?>
                	</tbody>              		
             	</table>
      		</div>
		</div>
	</div>
</div>