<?php
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- So that mobile will display zoomed in -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- enable media queries for windows phone 8 -->
<meta name="format-detection" content="telephone=no">
<!-- disable auto telephone linking in iOS -->
<title>Masjid System Email</title>

<style type="text/css">
body {
	margin: 0;
	padding: 0;
	-ms-text-size-adjust: 100%;
	-webkit-text-size-adjust: 100%;
	  
	leftmargin: 0; 
	topmargin: 0; 
	marginwidth: 0; 
	marginheight : 0;
}

table {
	border-spacing: 0;
	
}
.container-padding {
	padding-left: 24px; 
	padding-right: 24px;
}
.container-padding header {
	font-family: Helvetica, Arial, sans-serif; 
	font-size: 24px; 
	font-weight: bold; 
	padding-bottom: 12px; 
	color: #24c92f; 
	
}
.container-padding content {
	padding-top: 12px; 
	padding-bottom: 12px; 
	background-color: #ffffff;
}
.title {
	font-family: Helvetica, Arial, sans-serif; 
	font-size: 18px; 
	font-weight: 600; 
	color: #374550;
}
.body-text{
	font-family: Helvetica, Arial, sans-serif; 
	font-size: 14px; 
	line-height: 20px; 
	text-align: left; 
	color: #333333
}
.container {
	width: 600px; 
	max-width: 600px
}
table td {
	border-collapse: collapse;
}

.ExternalClass {
	width: 100%;
}

.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font,
	.ExternalClass td, .ExternalClass div {
	line-height: 100%;
}

.ReadMsgBody {
	width: 100%;
	background-color: #ebebeb;
}

table {
	mso-table-lspace: 0pt;
	mso-table-rspace: 0pt;
}

img {
	-ms-interpolation-mode: bicubic;
}

.yshortcuts a {
	border-bottom: none !important;
	text-decoration: none;
}

@media screen and (max-width: 599px) {
	table[class="force-row"], table[class="container"] {
		width: 100% !important;
		max-width: 100% !important;
	}
}

@media screen and (max-width: 400px) {
	td[class*="container-padding"] {
		padding-left: 12px !important;
		padding-right: 12px !important;
	}
}

.ios-footer a {
	color: #aaaaaa !important;
	text-decoration: underline;
}
</style>

</head>
<body>
	<table width="100%" height="100%">
		<tr>
			<td align="center" valign="middle">
				<?php echo $this->getContent(); ?>
			</td>
		</tr>
	</table>
</body>
</html>